AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon ECR repositories for LinkedInClone backend services.

Resources:
  ProfileRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: linkedinclone-profile-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

  JobRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: linkedinclone-job-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

  ApplicationRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: linkedinclone-application-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

Outputs:
  ProfileRepositoryUri:
    Value: !GetAtt ProfileRepository.RepositoryUri
  JobRepositoryUri:
    Value: !GetAtt JobRepository.RepositoryUri
  ApplicationRepositoryUri:
    Value: !GetAtt ApplicationRepository.RepositoryUri
