/** Curated suggestions for Add Skill / chip inputs (subset of 100). */
export const COMMON_TECH_SKILLS: string[] = [
  'JavaScript',
  'TypeScript',
  'React',
  'Node.js',
  'Python',
  'Java',
  'Go',
  'Rust',
  'C++',
  'C#',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Kafka',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'GraphQL',
  'REST API',
  'FastAPI',
  'Django',
  'Flask',
  'Spring Boot',
  'HTML',
  'CSS',
  'Tailwind CSS',
  'Next.js',
  'Vue.js',
  'Angular',
  'Svelte',
  'Webpack',
  'Vite',
  'Jest',
  'Cypress',
  'Playwright',
  'Git',
  'CI/CD',
  'GitHub Actions',
  'Terraform',
  'Ansible',
  'Linux',
  'Bash',
  'System Design',
  'Microservices',
  'gRPC',
  'Elasticsearch',
  'Snowflake',
  'Databricks',
  'Apache Spark',
  'Airflow',
  'dbt',
  'Tableau',
  'Power BI',
  'pandas',
  'NumPy',
  'scikit-learn',
  'TensorFlow',
  'PyTorch',
  'LLM Ops',
  'MLOps',
  'Data Engineering',
  'ETL',
  'Machine Learning',
  'Deep Learning',
  'NLP',
  'Computer Vision',
  'A/B Testing',
  'Product Management',
  'Agile',
  'Scrum',
  'Figma',
  'UI Design',
  'UX Research',
  'Accessibility',
  'Security',
  'OAuth2',
  'OpenID Connect',
  'JWT',
  'Penetration Testing',
  'SOC 2',
  'HIPAA',
  'GDPR',
  'Observability',
  'OpenTelemetry',
  'Prometheus',
  'Grafana',
  'Datadog',
  'Sentry',
  'iOS',
  'Android',
  'Swift',
  'Kotlin',
  'Flutter',
  'React Native',
  'WebSockets',
  'Socket.io',
  'RabbitMQ',
  'NATS',
  'Cassandra',
  'DynamoDB',
  'BigQuery',
  'ClickHouse',
  'Apache Flink',
  'Hadoop',
  'Scala',
  'Ruby',
  'Rails',
  'PHP',
  'Laravel',
  'Solidity',
  'Blockchain',
  'Ethereum',
]
