export type CuratedAd = {
  id: string
  advertiser: string
  advertiserInitials: string
  headline: string
  body: string
  cta: string
  ctaUrl: string
  /** Tailwind gradient for logo circle: direction + from-/to- colors (e.g. `from-blue-500 to-purple-600`) */
  gradient: string
}

export const curatedAds: CuratedAd[] = [
  {
    id: 'ad-nimbus-ide',
    advertiser: 'Nimbus Labs',
    advertiserInitials: 'NL',
    headline: 'Ship code reviews your team will actually use',
    body: 'Nimbus brings AI-assisted diff summaries and one-click policy checks into your existing Git host. No migration drama.',
    cta: 'Try free',
    ctaUrl: 'https://example.com',
    gradient: 'from-sky-500 to-indigo-600',
  },
  {
    id: 'ad-contoso-cloud',
    advertiser: 'Contoso Cloud',
    advertiserInitials: 'CC',
    headline: 'Cut your us-east bill in half with intelligent autoscaling',
    body: "Contoso's control plane spots idle services before your CFO does. See savings estimates in 60 seconds—no card required.",
    cta: 'Get started',
    ctaUrl: 'https://example.com',
    gradient: 'from-cyan-500 to-blue-700',
  },
  {
    id: 'ad-fabrikam-bootcamp',
    advertiser: 'Fabrikam School of Code',
    advertiserInitials: 'FS',
    headline: 'Part-time program: backend with Go & distributed systems',
    body: "Evening cohorts, mentor-led, capstone is a real open-source module. Cohort 14 opens next month in SF & remote.",
    cta: 'Learn more',
    ctaUrl: 'https://example.com',
    gradient: 'from-violet-500 to-fuchsia-600',
  },
  {
    id: 'ad-northwind-summit',
    advertiser: 'Northwind',
    advertiserInitials: 'NW',
    headline: 'Platform Engineering Summit 2026 — early bird until July',
    body: "Two days in Seattle: service mesh, FinOps, and the humans behind the graphs. 40+ speakers, hands-on tracks.",
    cta: 'Claim offer',
    ctaUrl: 'https://example.com',
    gradient: 'from-amber-500 to-rose-600',
  },
  {
    id: 'ad-litware-taskai',
    advertiser: 'Litware',
    advertiserInitials: 'LW',
    headline: "Your standups, minus the 40-minute 'quick sync'",
    body: "Litware pulls action items from Slack and your calendar, nudges owners, and never writes another vague recap.",
    cta: 'Try free',
    ctaUrl: 'https://example.com',
    gradient: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'ad-tailspin-pixels',
    advertiser: 'Tailspin Design Co.',
    advertiserInitials: 'TD',
    headline: "Figma + brand tokens that pass AA without another review cycle",
    body: 'The Tailspin kit ships accessible palettes, type ramps, and dev-ready export for React and iOS. Teams at 1,200+ startups.',
    cta: 'Get started',
    ctaUrl: 'https://example.com',
    gradient: 'from-pink-500 to-orange-500',
  },
  {
    id: 'ad-wingtip-legal',
    advertiser: 'Wingtip',
    advertiserInitials: 'WT',
    headline: "Clause-level AI for contracts (your counsel still approves the send)",
    body: "Upload MSAs, flag risky language, and route to the right attorney queue. Built for in-house legal at growth-stage SaaS.",
    cta: 'Learn more',
    ctaUrl: 'https://example.com',
    gradient: 'from-slate-600 to-slate-800',
  },
  {
    id: 'ad-globex-edge',
    advertiser: 'Globex Edge',
    advertiserInitials: 'GE',
    headline: "Deploy closer to your users without managing another k8s cluster",
    body: "Push static and SSR workloads to 90+ PoPs with one `globex push`. Usage-based to the minute.",
    cta: 'Get started',
    ctaUrl: 'https://example.com',
    gradient: 'from-blue-600 to-cyan-400',
  },
  {
    id: 'ad-initech-arc',
    advertiser: 'Initech',
    advertiserInitials: 'IN',
    headline: "The spreadsheet your FP&A team swears isn't a spreadsheet",
    body: "Arc connects billing, headcount, and sales ops so leadership sees one rolling forecast—still exportable to Excel for Terry.",
    cta: 'Try free',
    ctaUrl: 'https://example.com',
    gradient: 'from-green-600 to-lime-500',
  },
  {
    id: 'ad-acme-trace',
    advertiser: 'Acme Observability',
    advertiserInitials: 'AO',
    headline: "Trace the slow query before your on-call PagerDuty dance",
    body: "Drop-in OpenTelemetry, anomaly alerts on p99, and a blameless postmortem template your SREs will actually use.",
    cta: 'Learn more',
    ctaUrl: 'https://example.com',
    gradient: 'from-red-500 to-orange-600',
  },
  {
    id: 'ad-nimbus-relay',
    advertiser: 'Nimbus Relay',
    advertiserInitials: 'NR',
    headline: "API mocks that match prod traffic shapes (and stay in sync)",
    body: "Record production-safe samples, version them in Git, and spin envs in CI so flaky integration tests become rare birds.",
    cta: 'Get started',
    ctaUrl: 'https://example.com',
    gradient: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'ad-fabrikam-hw',
    advertiser: 'Fabrikam',
    advertiserInitials: 'FB',
    headline: "The 14\" dev laptop: 64GB RAM, Linux-first, all-day battery",
    body: "CNC unibody, repairable, two Thunderbolt 4, optional matte display. Waitlist for batch B opens Friday.",
    cta: 'Claim offer',
    ctaUrl: 'https://example.com',
    gradient: 'from-zinc-700 to-stone-900',
  },
  {
    id: 'ad-lumina-ai',
    advertiser: 'Lumina (by Litware)',
    advertiserInitials: 'LA',
    headline: "Inline docs that update when your code does—seriously",
    body: "Lumina pairs with your repo, suggests README diffs, and nudges outdated ADRs. Works with Jira, Linear, and calm teams.",
    cta: 'Try free',
    ctaUrl: 'https://example.com',
    gradient: 'from-fuchsia-500 to-pink-600',
  },
  {
    id: 'ad-northwind-data',
    advertiser: 'Northwind Analytics',
    advertiserInitials: 'NA',
    headline: "Warehouse syncs that finish before the coffee cools",
    body: "CDC from Postgres and Snowflake with schema drift caught at staging—your analysts stop trusting spreadsheets named final_v2.",
    cta: 'Learn more',
    ctaUrl: 'https://example.com',
    gradient: 'from-blue-400 to-blue-600',
  },
  {
    id: 'ad-contoso-secure',
    advertiser: 'Contoso Secure',
    advertiserInitials: 'CS',
    headline: "Secrets rotation without the 2am 'who broke prod?'",
    body: "Policy-driven rollouts, audit trails your SOC 2 friends love, and a panic button that revokes in seconds, not sprints.",
    cta: 'Get started',
    ctaUrl: 'https://example.com',
    gradient: 'from-red-600 to-rose-800',
  },
]
